# Generated by Django 4.2.11 on 2024-04-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='representante',
            new_name='distribuidor',
        ),
    ]
