# Generated by Django 4.2.11 on 2024-04-11 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0004_avaliacao_produto_alter_produto_distribuidor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosimagens',
            name='Produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtosimagens',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Produtos.produto'),
            preserve_default=False,
        ),
    ]
