# Generated by Django 4.2.11 on 2024-04-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0005_remove_produtosimagens_produto_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
