# Generated by Django 4.2.11 on 2024-04-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0006_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
