# Generated by Django 4.2.11 on 2024-04-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0007_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
