# Generated by Django 4.2.11 on 2024-04-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0002_alter_fornecedor_representante'),
        ('Produtos', '0008_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='distribuidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='Fornecedores.fornecedor'),
        ),
    ]
