# Generated by Django 4.2.11 on 2024-04-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0009_alter_produto_distribuidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosimagens',
            name='slot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
