# Generated by Django 4.2.10 on 2024-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('representante', models.CharField(max_length=70)),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=70)),
                ('pais', models.CharField(max_length=80)),
            ],
        ),
    ]
