# Generated by Django 4.2.10 on 2024-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=70)),
                ('data_nascimento', models.DateTimeField()),
                ('e_mail', models.CharField(max_length=70)),
                ('cpf', models.IntegerField(max_length=15)),
                ('senha', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField(max_length=8)),
                ('complemento', models.CharField(max_length=80)),
            ],
        ),
    ]
