# Generated by Django 4.2.10 on 2024-04-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='e_mail',
            new_name='email',
        ),
    ]
