# Generated by Django 4.2.11 on 2024-04-10 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_perfilimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilimages',
            name='caption',
        ),
        migrations.AddField(
            model_name='perfilimages',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagensperfil', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
