# Generated by Django 4.2.11 on 2024-04-10 22:53

import Clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_perfilimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Clientes.models.user_directory_path),
        ),
    ]
